# Created by trellis-cli v1.14.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  lucianotigre.com.br:
    site_hosts:
    - canonical: lucianotigre.test
      redirects:
      - www.lucianotigre.test
    local_path: ../site
    admin_email: admin@lucianotigre.test
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: self-signed
    cache:
      enabled: false
