# Created by trellis-cli v1.14.1
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  lucianotigre.com.br:
    site_hosts:
    - canonical: lucianotigre.com.br
      redirects:
      - www.lucianotigre.com.br
    local_path: ../site
    branch: master
    repo: git@github.com:example/example.com.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: false
      provider: letsencrypt
    cache:
      enabled: false
